---
title: "HOMEWORK_2"

---
*Funciones en R*
  Estructura de una función
  Toda función tiene cuatro componentes:

  *Nombre: para usar una función hay que llamarla por su nombre.
  *Argumentos: los argumentos le indican a la función sobre quién y cómo realizará su tarea específica.
  *Cuerpo: en el cuerpo se define qué es lo que hace la función.
  *Salida: la salida es el resultado final de la función.
  ---
  Ejemplo:
  
```{r}
sumar2 <- function (arg1, arg2) {
   #Aquí va el cuerpo de la función
   salida <- arg1 + arg2
   return(salida)
   #La función return() sirve para especificar la salida de las funciones
}
```
---
Argumentos de una función
Los argumentos son las variables que necesita la función para realizar sus operaciones. Aparecen entre paréntesis, separados por comas. Los valores son asignados al nombre del argumento por el usuario cada vez que ejecuta una función.
---
Argumentos por valor
Los argumentos pueden ser datos, estructuras de datos, conexiones a archivos u otras funciones y todos deben tener nombres diferentes.
---
*Family apply*
La familia de funciones apply es usada para aplicar una función a cada elemento de una estructura de datos. En particular, es usada para aplicar funciones en matrices, data frames, arrays y listas.

Con esta familia de funciones podemos automatizar tareas complejas usando poca líneas de código y es una de las características distintivas de R como lenguaje de programación.

*Lapply
Es un caso especial de apply(), diseñado para aplicar funciones a todos los elementos de una lista. La l de su nombre se refiere, precisamente, a lista.

lapply() intentará coercionar a una lista el objeto que demos como argumento y después aplicará una función a todos sus elementos.

A <- matrix(1:9,nrow = 3, ncol = 3)
B <- matrix(11:19,nrow = 3, ncol = 3)
C <- matrix(21:29,nrow = 3, ncol = 3)
mi_lista <- list(A,B,C)
lapply(mi_lista,"[",1,1)
[[1]]
[1] 1

[[2]]
[1] 11

[[3]]
[1] 21

*Sapply
Se diferencia con apply en que opera con listas. Recibe una lista y devuelve un vector

Ejemplo 1:
sapply(mi_lista,"[",1,1)
[1]  1 11 21

*Vapply
Devuelve un vector con la longitud que tiene cada una de las listas introducidas como parámetro.

x <- list(A = 1, B = 1:3, C = 1:7)
x
$a
[1] 1
$b
[1] 1 2 3
$c
[1] 1 2 3 4 5 6 7

vapply(x, FUN = length, FUN.VALUE = 0L)
a b c 
1 3 7