
```{r}
library(tidyverse)
library(dplyr)

answers <- read_csv('answers.csv')
question_tags <- read_csv('question_tags.csv')
questions <- read_csv('questions.csv')
tags <- read_csv('tags.csv')
```

```{r}
#Left-joining questions and tags

questions
question_tags 

questions %>% 
  left_join(question_tags, by=c("id" = "question_id"))

```

```{r}
questions %>% 
  left_join(tags, by="id") %>%
  left_join(question_tags, by=c("id" = "question_id"))
```

```{r}
questions_with_tags <-questions %>% 
  left_join(question_tags, by=c("id" = "question_id")) %>%
  left_join(tags, by="id") %>%
  mutate(tag_name = replace_na("only-r"))

questions_with_tags
```

```{r}
#Comparing scores across tags

questions_with_tags %>%
  group_by(tag_name) %>%
  summarise(mean_score = mean(score)) %>%
  arrange(desc(mean_score))

```

```{r}
#Finding gaps between questions and answers

questions %>% 
  inner_join(answers, by=c("id"="question_id"),  suffix=c("_question","_answer")) %>%
  mutate(gap = creation_date_answer - creation_date_question)

```

```{r}
#Joining question and answer counts

answer_counts <- answers %>%
  count(question_id)
```


```{r}
question_answer_counts <- questions %>% 
  left_join(answer_counts, by=c("id" = "question_id")) %>%
  mutate(n = replace(n, is.na(n),0))

question_answer_counts
```

```{r}
#Joining questions, answers, and tags

question_tags %>% 
  inner_join(question_answer_counts, by= c("question_id" = "id")) %>%
  inner_join(tags, by = c("question_id" = "id"))

```

